### PR TITLE
DBParameterGroupName support

### PR DESCRIPTION
**Pull request by ambsw-technology**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

This locates module parameters where they're found in `aws-cf-templates` and resource parameters in the order found on the `AWS::` resource page.

### CODE REVIEW

**Comment by ambsw-technology** [comment]
Just noticed that you build a parameter group.  Let me do some digging to figure out how to best incorporate additional items like SSL.

**Comment by ambsw-technology** [comment]
Sounds like I need some clarification from you.  For postgres serverless the only setting that's created in the Cluster group seems to match the default:

image

Why is the group being created this way?

**Comment by ambsw-technology** [comment]
I was also looking at the base `rds-aurora` template in `aws-cf-templates` since `cfn-modules` doesn't appear to have an equivalent and there appears to be a `DBParameterGroup` (instance not `Cluster`) as well that sets no parameters:

```
  DBParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: !Ref 'AWS::StackName'
      Family: !FindInMap [EngineMap, !Ref Engine, ParameterGroupFamily]
```

I assume this makes it equivalent to the `default.*` parameter groups.

**Comment by michaelwittig** [comment]
test

**Review by michaelwittig — CHANGES_REQUESTED** [review]
LGTM! Could you add the new parameter to the README.md?

**Comment by michaelwittig** [comment]
> Sounds like I need some clarification from you. For postgres serverless the only setting that's created in the Cluster group seems to match the default:
> Why is the group being created this way?

Honestly, I can't remember. But your solution increases flexibility without interrupting existing deployments 👍

**Comment by michaelwittig** [comment]
@ambsw-technology is this ready to be merged?

**Comment by ambsw-technology** [comment]
Added README.  Yes I think it's ready.

**Pull request merged**
